openapi: 3.0.0
info:
  title: MOKURA
  version: 1.0.0
servers:
  - url: http://3.89.63.60:6969
tags:
  - name: logging
  - name: user
  - name: mokura
paths:
  /logging/datalist:
    post:
      tags:
        - logging
      summary: Insert Data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                time_stamp: test_time_stamp
                lat: test_lat
                lon: test_lon
                compass: test_compass
                speed: test_speed
                rpm: test_rpm
                battery: test_battery
                duty_cycle: test_duty_cycle
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /logging:
    get:
      tags:
        - logging
      summary: Get All Mokura Logging Data
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users:
    get:
      tags:
        - user
      summary: Get one user by email
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/register:
    post:
      tags:
        - user
      summary: Register user
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                email:
                  type: string
                  example: vitorizki37@gmail.com
                username:
                  type: string
                  example: vito
                password:
                  type: string
                  example: '{{password}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/login:
    post:
      tags:
        - user
      summary: Login user
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                email:
                  type: string
                  example: vitorizki37@gmail.com
                password:
                  type: string
                  example: '{{password}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mokura:
    get:
      tags:
        - mokura
      summary: Get a hardware by hardware name
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mokura/register:
    post:
      tags:
        - mokura
      summary: Register Mokura Hardware
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                hardware_serial:
                  type: string
                  description: Hardware mac address
                  example: B8:27:EB:BB:61:82
                hardware_name:
                  type: string
                  description: Hardware name
                  example: raspberrypi
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}