version: '3'

volumes:
  mariadb:
    driver: local
  mosquitto_data:
  mosquitto_log:

networks:
    db:
        driver: host
        
services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: vito
      MYSQL_PASSWORD: 123
    expose:
        - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "80"
    ports:
      - "80:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306

  mqtt-broker:
    image: eclipse-mosquitto:1.6
    restart: always
    expose:
      - "1883"
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    
  script:
    build: .
    expose:
      - "1883"




