version: '3'

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: vito
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - mqtt_network       

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "80:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      - mqtt_network  
  # mqtt-broker:
  #   image: eclipse-mosquitto
  #   ports:
  #     - "1883:1883"
  #   restart: always
  mqtt-broker:
    build: .
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - mqtt_network

# volumes:
#   mariadb:

networks:
  mqtt_network:

volumes:
  mariadb:
  mosquitto_data:
  mosquitto_log:

# version: '3'

# services:
#   mariadb:
#     image: mariadb:10.6
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: test
#     expose:
#       - "3306"
#     ports:
#       - "3306:3306"
#     volumes:
#       - mariadb_data:/var/lib/mysql
#     networks:
#       - mqtt_network

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     restart: always
#     environment:
#       PMA_HOST: mariadb
#       PMA_PORT: 3306
#     ports:
#       - "8080:80"
#     networks:
#       - mqtt_network

#   mqtt-broker:
#     image: eclipse-mosquitto
#     restart: always
#     ports:
#       - "1883:1883"
#     volumes:
#       - mosquitto_data:/mosquitto/data
#       - mosquitto_log:/mosquitto/log
#     networks:
#       - mqtt_network

# networks:
#   mqtt_network:

# volumes:
#   mariadb_data:
#   mosquitto_data:
#   mosquitto_log:
