version: '3'

volumes:
  mariadb:
    driver: local

networks:
    db:
        driver: host

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER:  vito
      MYSQL_PASSWORD: 123
    expose:
        - "3306"
    ports:
        - "3306:3306"
    volumes:
     - mariadb:/var/lib/mysql
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      db:

  